[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["mymirro-chat-api/**"]

[deploy]
healthcheckPath = "/api/health_check"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

